### ISSUE TITLE
Spent fuel and rad pollution issue

### ISSUE THREAD

**Issue by Extreme159** [NotoriousPyro/NuclearPlus#2]
Hi! Thanks for the mod, i liked it and i have an idea for it. On current status, spent fuels are processed in chemical plant together with nitric acid. The problem is, work cycle for this job is "10 Spent Fuel + 10 Nitric Acid = 20 Spent fuel solution (/20 game time)", and to cycle to start, 10 spent fuels must be transferred into chemical plant. Until spent fuels get the count of 10, they stay inside the chemical plant and cause a radiation pollution. Radiation pollution graph is repeatedly rising until 18 (9xspent fuel) and falling back to 0 (10 spent fuel start to process)

So, can you please edit spent fuel cycle like this?
"1 Spent fuel + 1 Nitric Acid = 2 Spent fuel solution (/2 game time)"  so /60 input and output will be same but any spent fuel get in to the chemical plant will start to process without waiting a batch of 10 spent fuel and causing a rad pollution.

Have a great day!

![radpollution](https://user-images.githubusercontent.com/123478453/214323142-c7cc59e0-ae6b-422a-8446-cd536797de63.jpg)

**Comment by NotoriousPyro** [comment]
I had made this intentional, as there has to be some drawbacks to getting "free" fuel. But I will have a think about the balance a bit and let others comment on their thoughts.

**Comment by NotoriousPyro** [comment]
Can you give me more insight into how radiation affects the game and how running this mod for some time has influenced, if at all, the gameplay?

I'm wondering how balanced my intentions were.

**Comment by Extreme159** [comment]
Hi again, this level of radiation doesn't have any negative effects. Only can be seen on pollution graphs. If rad pollution stacks more( not limited to 18 and reset), people will get sick and also deaths occur. But i don't know the exact number when people start to get sick or die.

**Comment by NotoriousPyro** [comment]
Won't do anything with this, possibly if it has negative effects then I may revisit it.
